insert into sound_effect (regex, description, abbreviation, filename) values
("^al?les [dt]uets m[ei]?r weh?$", "alles tuets mir weh", "atmw", "alles_tuets_mir_weh.ogg"),
("^((are|r) you (gonna|going?'? to) finish that )?croissant\\??$", "are you gonna finish that croissant?", "gipfeli", "are_you_going_to_finish_that_croissant.ogg"),
("^(n[eä]i,? )?angs(ch)?t und gäl[dt] han ?i{1,2}ch k[eä]i$", "angst und gäld hanich kei", "aughk", "angst_und_gäld_hanich_kei.ogg"),
("^are y(a|ou) winnin[g']? son\\??$", "are ya winning son?", "ayws", "are_ya_winning_son.ogg"),
("^chantal heul'? leise!?$", "chantal heul leise", "chl", "chantal_heul_leise.ogg"),
("^chum da h[eä]re,?(( chum)? du hue?resoh?n)?!?$", "chum da here du hueresohn", "cdhdh", "chum_da_here_du_hueresohn.ogg"),
("^(choo choo,? )?(hier kommt [bj]ulien [bj]am|wir fahren in die tre-?h?e?nds)$", "choo choo wir fahren in die trends", "wfidt", "choo_choo_wir_fahren_in_die_trends.ogg"),
("^computer sagt ne{1,}in$", "computer sagt nein", "csn", "computer_sagt_nein1.ogg"),
("^das is(ch|t) gugus([\\.,]? (gugus )?gsi,?( gugus geblie?ben?)?)?$", "das isch gugus", "gugus", "das_isch_gugus.ogg"),
("^ega+l$", "egal", "egal", "egal.ogg"),
("^hello there$", "hello there", "ht", "hello_there.ogg"),
("^gurke f[aä]ngt au(ch)? mi[dt] g an?$", "gurke fangt au mid g a", "gfamga", "gurke_fangt_auch_mit_g_a.ogg"),
("^(it'?s ov(er|a) anakin,? )?i have the high ground!?$", "i have the high ground", "ihthg", "i_have_the_high_ground.ogg"),
("^i like yo(ur?)? (coochie?|cut g)$", "i like your coochie", "ilyc", "i_like_you_coochie.ogg"),
("^i'?m(m?a| gonna| goin[g']? to) say the n[ -]?word$", "i'm gonna say the nword", "nword", "im_gonna_say_the_nword.ogg"),
("^(i'?m(m?a| gonna| goin[g']? to) do (what'?s called )a )?pro[- ]?gamer move$", "i'm gonna do a pro gamer move", "pgm", "im_gonna_do_a_pro_gamer_move.ogg"),
("^ich bin? k[eä]i hue?resoh?n$", "ich bin kei hueresohn", "ibkh", "ich_bin_kei_hueresohn.ogg"),
("^(mrs|misses) obama get down$", "mrs Obama get down", "mogd", "mrs_obama_get_down.ogg"),
("^(muesch di (eifach chli )?benä (wie? ?ne) grosse bueb|denis)$", "muesch die eifach chli benä wine grosse bueb", "mdb", "muesch_di_benä.ogg"),
("^ok$", "ok", "ok", "ok1.ogg"),
("^oke$", "oke", "oke", "oke.ogg"),
("^((ja )?richi,? i ha gseit du sö(u|ll)sch di guet häb[äe]|richi häb di|richi)!*$", "richi häb di!", "richi", "richi_häb_di.ogg"),
("^(shut up ?){1,2}!?$", "shut up!", "su", "shut_up_shut_up.ogg"),
("^(sorr?y,? )?i(ch)? habe gesprit?zt$", "sorry ich habe gespritzt", "sihg", "sorry_ich_habe_gespritzt.ogg"),
("^(thanks|thx|thenx) obama$", "thanks obama", "to", "thanks_obama.ogg"),
("^permission denied$", "permission denied", "pd", "permission_denied.ogg"),
("^upgrades,? people( upgrades)?!?$", "upgrades people!", "up", "upgrades_people.ogg"),
("^you('?ve| have) been st(ah?|o)pped!?$", "you have been stopped", "yhbs", "you_have_been_stopped.ogg"),
("^you underestimate my power!?$", "you underestimate my power", "yump", "you_underestimate_my_power.ogg"),
("^yo(ur?)? mom('?s)? a (whore|hoe?)$", "your mom's a hoe", "ymah", "your_moms_a_hoe.ogg"),
("^(you|u) (are|r) ga[ey]$", "you are gay", "yag", "you_are_gay.ogg"),
("^w[ao]s k[oa]nnst du (eigentlich|eigl\\.?)\\??$", "was kannst du eigentlich?", "wkde", "was_kannst_du_eigentlich.ogg"),
("^(wh)?y (are|r) (yo)?u ga[ey]\\??$", "why are you gay?", "wayg", "why_are_you_gay.ogg"),
("^zapzarap{1,2} anzeige$", "zapzarap anzaige", "zzr", "zapzarap_anzeige.ogg")
;
